version: '3'

tasks:
  build:
    cmds:
      - tsc -p ./tsconfig.json --module es2015 --outDir ./dist/esm && tsc -p ./tsconfig.json --module commonjs --outDir ./dist
      - cp ./LICENSE ./dist/LICENSE
      - cp ./README.md ./dist/README.md
      - cp ./package.json ./dist/package.json
      - touch ./package-temp.json
      - jq '.types = "./esm/index.d.ts"' ./dist/package.json > ./package-temp.json
      - mv ./package-temp.json ./dist/package.json
  publish:
    cmd: npm publish ./dist --access public